language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
env:
  global:
  - secure: ebS8NqVr8Zp24F3Dtv0xQPVoDlmRbOiw7mMP7ECkDYbnue5+UlB5Ca6lZA/LPDaFTXCee0Gkay6wHJUou6gu20GtL4HZ8/htbUcND2vqo2bmxxYsIWfnVgXUgpGIFl/su2l1I/TGet0OvGl0fQS9nlnDzIp3Iypzwbnz0QYp4VI=
  - secure: Xhg1GtbTb3iebjhzgNizhM4OHhY7ZM+gcgta4N5t0ux1NsRpjsUth3F/B/TvCMO0Eo6imr/ZrkT0BCkvVlWOBe5zJX65mXEMoEPBLEuUj2rUYyve9iPWOUmy/egPkzhExOd+8c6S/ZkedqtsAwTt8JGv0s0uvmK0CvHZAjQOpkU=
